services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/copy2
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      YANDEX_API_KEY: ${YANDEX_API_KEY}
      YANDEX_FOLDER_ID: ${YANDEX_FOLDER_ID}
      SYNONYM_SERVICE_URL: http://synonym-checker:8000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - synonym-checker
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - "3000:80"
    networks:
      - app-network

  synonym-checker:
    build: ./synonym-checker
    ports:
      - '8000:8000'
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8000/docs' ]
      interval: 30s
      retries: 3
    networks:
      - app-network
networks:
  app-network:

volumes:
  postgres_data: