CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255)        NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255)        NOT NULL,
    role          VARCHAR(255),
    photo_url     VARCHAR(255),
    created_at    TIMESTAMP           NOT NULL,
    updated_at    TIMESTAMP           NOT NULL
);

CREATE TABLE user_statistics
(
    user_id         BIGINT PRIMARY KEY,
    total_answers   BIGINT  DEFAULT 0,
    correct_answers BIGINT  DEFAULT 0,
    current_streak  INTEGER DEFAULT 0,
    longest_streak  INTEGER DEFAULT 0,
    last_test_date  DATE,
    CONSTRAINT fk_stats_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE activity_logs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    test_id      BIGINT,
    attempt_date TIMESTAMP NOT NULL,
    score        INT       NOT NULL,
    total        INT       NOT NULL,
    CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_logs_test FOREIGN KEY (test_id) REFERENCES tests (id)
);

CREATE TABLE tests
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name     VARCHAR(255) NOT NULL,
    user_id       BIGINT,
    description   TEXT,
    visible       BOOLEAN,
    access_mode   VARCHAR(255) NOT NULL DEFAULT 'PRIVATE',
    share_token   VARCHAR(50) UNIQUE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_tests_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE test_accesses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id      BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    access_level VARCHAR(255) NOT NULL DEFAULT 'READ',
    shared_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_test_accesses_test FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE,
    CONSTRAINT fk_test_accesses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE questions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id       BIGINT,
    content       TEXT      NOT NULL,
    question_type VARCHAR(255),
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    CONSTRAINT fk_questions_test FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
);

CREATE TABLE answers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT,
    content     TEXT      NOT NULL,
    is_correct  BOOLEAN   NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
);

CREATE TABLE test_sessions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    test_id       BIGINT,
    correct_count BIGINT    NOT NULL DEFAULT 0,
    total_count   BIGINT    NOT NULL DEFAULT 0,
    started_at    TIMESTAMP NOT NULL,
    finished_at   TIMESTAMP,
    CONSTRAINT fk_test_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_test_sessions_test FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE SET NULL
);

CREATE TABLE user_answers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_session_id BIGINT,
    question_id     BIGINT,
    correct         BOOLEAN   NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_answers_session FOREIGN KEY (test_session_id) REFERENCES test_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_answers_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE SET NULL
);

CREATE TABLE notification_settings
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type    VARCHAR(255) NOT NULL,
    test_id BIGINT,
    user_id BIGINT,
    CONSTRAINT fk_settings_test FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE,
    CONSTRAINT fk_settings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE notifications
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_settings_id BIGINT       NOT NULL,
    version                  INT          NOT NULL DEFAULT 0,
    sent_at                  TIMESTAMP    NOT NULL,
    status                   VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    error_message            VARCHAR(255),
    CONSTRAINT fk_notifications_settings FOREIGN KEY (notification_settings_id)
        REFERENCES notification_settings (id) ON DELETE CASCADE
);


CREATE TABLE verification_codes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255)        NOT NULL,
    email       VARCHAR(255) UNIQUE NOT NULL,
    expiry_date TIMESTAMP           NOT NULL
);

CREATE INDEX idx_notifications_status_time ON notifications (status, sent_at);