spring.application.name=copy2

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/copy2
spring.datasource.username=postgres
spring.datasource.password=${DATABASE_PASSWORD}
spring.sql.init.mode=always

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# WEB
logging.level.org.springframework.web=DEBUG

spring.mail.host=${MAIL_HOST:smtp.mail.ru}
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true

