name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [backend, frontend]
    outputs:
      backend_tag: ${{ steps.meta.outputs.backend_image }}
      frontend_tag: ${{ steps.meta.outputs.frontend_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Image Tags
        id: meta
        run: |
          REPO="${{ github.repository }}"
          LOWER_REPO="${REPO,,}"
          IMAGE_TAG="main-${{ github.sha }}-${{ github.run_number }}"
          FULL_IMAGE="ghcr.io/${LOWER_REPO}/${{ matrix.service }}:${IMAGE_TAG}"
          
          echo "image=${FULL_IMAGE}" >> $GITHUB_OUTPUT
          echo "${{ matrix.service }}_image=${FULL_IMAGE}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.image }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_HOST: ${{ vars.MAIN_DOCKER_HOST }}
      BACKEND_IMAGE: ${{ needs.build.outputs.backend_tag }}
      FRONTEND_IMAGE: ${{ needs.build.outputs.frontend_tag }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Remote Deploy
        run: |
          ssh bogdan@${{ secrets.VM_IP }} "cd ~/t-prep && git pull origin main && \
          export BACKEND_IMAGE=${{ env.BACKEND_IMAGE }} && \
          export FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }} && \
          docker compose pull && docker compose up -d"